### ISSUE TITLE
Neutral button stops firing (iOS)

### ISSUE THREAD

**Issue by apgsn** [gusparis/react-native-month-year-picker#57]
Hello again Gustavo,
I've been noticing an odd behavior on iOS with the neutral button you added in #48. Sometimes, after I've been using my app for a while, the button just stops firing the `NEUTRAL_ACTION` event. Unfortunately I don't have a code snippet to show you to replicate the problem, but it happens quite regularly and I'm still trying to figure out why. I'll keep you posted on the matter.
Cheers.

**Comment by gusparis** [comment]
Hey @apgsn ! How's it going?
That's some weird behavior you have there. Let me check. I think I might know why this is happening.

**Comment by gusparis** [comment]
@apgsn I tried the component for about 15 min, and the neutral action is firing as expected. Please update with the steps to reproduce it once you have them. 👋🏼 👋🏼 👋🏼

**Comment by apgsn** [comment]
Thanks for looking into it! Next week I'll see if I can find a way to replicate the bug consistently.

**Comment by gusparis** [comment]
Closed due to inactivity. Reopen if needed.

**Comment by SmirnovM91** [comment]
Hello, I have the same problem

**Comment by SmirnovM91** [comment]
I've fixed it by replacing `nil` to `self` at 41 line in RNMonthPicker+Toolbar.m

`UIBarButtonItem *neutralButton = [[UIBarButtonItem alloc] initWithTitle:_neutralButtonLabel style:UIBarButtonItemStylePlain target:self action:@selector(onNeutralButton)];`

**Comment by PunainenAurinko** [comment]
This is still happening in v.1.6.4. After a while of use (multiple month/year) combinations being selected, the neutral button click stops triggering any event at all. I think the above code would fix this issue. Is it possible to make that change in the module?

**Comment by PunainenAurinko** [comment]
@gusparis Hi Gustavo, why was this closed? This issue is still happening in v. 1.6.4. Neutral button randomly stops firing on iOS (I'm on 14.6). SmirnovM91 solution works but needs to be included in the library as a PR.
